// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"time"
)

type User struct {
	Username          string
	Role              string
	HashedPassword    string
	FullName          string
	Email             string
	IsEmailVerified   bool
	PasswordChangedAt time.Time
	CreatedAt         time.Time
}

type VerifyEmail struct {
	ID         int64
	Username   string
	Email      string
	SecretCode string
	IsUsed     bool
	CreatedAt  time.Time
	ExpiredAt  time.Time
}
