// Code generated by MockGen. DO NOT EDIT.
// Source: internal/application/verify_email_repository.go

// Package mockdb is a generated GoMock package.
package mockdb

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/lucasHSantiago/go-ecommerce-ms/auth/internal/domain"
	params "github.com/lucasHSantiago/go-ecommerce-ms/auth/internal/params"
)

// MockVerifyEmailRepository is a mock of VerifyEmailRepository interface.
type MockVerifyEmailRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVerifyEmailRepositoryMockRecorder
}

// MockVerifyEmailRepositoryMockRecorder is the mock recorder for MockVerifyEmailRepository.
type MockVerifyEmailRepositoryMockRecorder struct {
	mock *MockVerifyEmailRepository
}

// NewMockVerifyEmailRepository creates a new mock instance.
func NewMockVerifyEmailRepository(ctrl *gomock.Controller) *MockVerifyEmailRepository {
	mock := &MockVerifyEmailRepository{ctrl: ctrl}
	mock.recorder = &MockVerifyEmailRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVerifyEmailRepository) EXPECT() *MockVerifyEmailRepositoryMockRecorder {
	return m.recorder
}

// CreateVerifyEmail mocks base method.
func (m *MockVerifyEmailRepository) CreateVerifyEmail(ctx context.Context, arg params.CreateVerifyEmailRepo) (*domain.VerifyEmail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVerifyEmail", ctx, arg)
	ret0, _ := ret[0].(*domain.VerifyEmail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVerifyEmail indicates an expected call of CreateVerifyEmail.
func (mr *MockVerifyEmailRepositoryMockRecorder) CreateVerifyEmail(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVerifyEmail", reflect.TypeOf((*MockVerifyEmailRepository)(nil).CreateVerifyEmail), ctx, arg)
}

// UpdateVerifyEmail mocks base method.
func (m *MockVerifyEmailRepository) UpdateVerifyEmail(ctx context.Context, arg params.UpdateVerifyEmailRepo) (*domain.VerifyEmail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVerifyEmail", ctx, arg)
	ret0, _ := ret[0].(*domain.VerifyEmail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateVerifyEmail indicates an expected call of UpdateVerifyEmail.
func (mr *MockVerifyEmailRepositoryMockRecorder) UpdateVerifyEmail(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVerifyEmail", reflect.TypeOf((*MockVerifyEmailRepository)(nil).UpdateVerifyEmail), ctx, arg)
}

// VerifyEmailTx mocks base method.
func (m *MockVerifyEmailRepository) VerifyEmailTx(ctx context.Context, arg params.VerifyEmailTxRepo) (params.VerifyEmailTxRepoResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyEmailTx", ctx, arg)
	ret0, _ := ret[0].(params.VerifyEmailTxRepoResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyEmailTx indicates an expected call of VerifyEmailTx.
func (mr *MockVerifyEmailRepositoryMockRecorder) VerifyEmailTx(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyEmailTx", reflect.TypeOf((*MockVerifyEmailRepository)(nil).VerifyEmailTx), ctx, arg)
}
